### ISSUE TITLE
Manter a connection e o channel

### ISSUE THREAD

**Issue by houstondapaz** [Otavioensa/rabbit-workers-talk#1]
Oi Otavio tudo bem?
Muito boa a talk, parabéns!

Estou começando a trabalhar com rabbit e uma das duvidas que eu tenho é se reutilizo sempre o mesmo channel e connection ou se fecho e reabro eles sempre que for mandar uma msg.

Abras

**Comment by Otavioensa** [comment]
Ola @houstondapaz ! 
Perdão pela demora em responder!
Para a publicação de mensagens, faz mais sentido voce abrir e fechar uma conexão a cada vez que precisar executar esse passo. Esse tipo de processamento é tido como leve pelo rabbit.
Por outro lado, se precisar consumir a mensagens, tera que abrir uma conexao amqp e tratar a mensagem que chega!
Espero poder ter ajudado! : )
